version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID-1000}
        GID: ${GID-1000}
        INSTALL_XDEBUG: ${INSTALL_XDEBUG-false}
    container_name: laravel6-app
    working_dir: /var/www/www/rosie
    volumes:
      - ./:/var/www
    networks:
      - laravel6
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: laravel6-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - laravel6

  db:
    image: mysql:8.0
    container_name: laravel6-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    ports:
      - "33060:3306" # opcional: acessa via host (TablePlus/Workbench)
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel6

networks:
  laravel6:
    driver: bridge

volumes:
  dbdata:
